### ISSUE TITLE
does this integrates with databricks

### ISSUE THREAD

**Issue by hardiktalati** [cerndb/spark-dashboard#1]
Hey Luca, 

It offers more like overwatch from databricks - i use stagemetrics with databricks and localhost. I would like to do the same with spark-dashboard, deploy docker on container instance in azure and somehow integrate with databricks... is it possible or  i am on a wrong track.

**Comment by LucaCanali** [comment]
I dont' have the possibility to test this at present, however, it should work. Spark dashboard uses the Apache Spark metrics system with the GraphiteSink, then an instance of InfluxDB 1.x is used in my implementation to capture those metrics. As long as Spark (driver and executors) can communicate with InfluxDB (typically on port 2003) that should work.
