### ISSUE TITLE
Inconsistency in Spark Dashboard

### ISSUE THREAD

**Issue by mittal-yash** [cerndb/spark-dashboard#2]
Hi Luca,

I am using Spark Dashboard to monitor spark jobs that are using spark 2.2.0. We are running jobs in yarn. In cluster mode inconsistency is observed. For some jobs metrics is showing in dashboard and for some jobs metrics is not coming. Can you please guide.

**Comment by LucaCanali** [comment]
Hi,
I am glad to hear you are using the Spark Dashboard. However, I am afraid Spark 2.2.0 is quite an old version of Spark and several metrics used in the dashboard have been introduced in Spark 2.3.0 and 2.4.0.
Best,
Luca

**Comment by mittal-yash** [comment]
Hi Luca,

Can you please suggest how to enable logs in spark dashboard.

**Comment by LucaCanali** [comment]
I am afraid that the are no specific logs for the dashboard itself, but it relies on logging from the components (Spark, Influx, Grafana).

**Comment by mittal-yash** [comment]
Thank you for the info
