### ISSUE TITLE
influxdb failed to start

### ISSUE THREAD

**Issue by sxcooler** [cerndb/spark-dashboard#3]
Hi luca,
I tried to start spark-dashboard under CentOS 7.6 / Docker / Containerd, and container logs said "influxdb was unable to start", I entered container bash and found that /var/log/influxdb/influxd.log shows:
`run: open server: listen tcp 127.0.0.1:8088: bind: address already in use`
that port 8088 was taken by my Hadoop Resource Manager.
But I searched the whole repo of spark-dashboad, found nothing "8088", is there any way to customize this config?

**Comment by LucaCanali** [comment]
Hi,
thanks for reporting this, indeed I confirm the issue of port 8088 being allocated, although not needed when running the spark-dashboard container image with network=host. Please try to start the container using:
`docker run -p 3000:3000 -p 2003:2003 -d lucacanali/spark-dashboard:v01`
Best,
Luca

**Comment by sxcooler** [comment]
> Hi, thanks for reporting this, indeed I confirm the issue of port 8088 being allocated, although not needed when running the spark-dashboard container image with network=host. Please try to start the container using: `docker run -p 3000:3000 -p 2003:2003 -d lucacanali/spark-dashboard:v01` Best, Luca

Thank you for reply, It's OK now.
