### ISSUE TITLE
Using Spark 3.3 seems that I have empty dashboards -- tested the V1 and latest version 

### ISSUE THREAD

**Issue by mdtmailgr** [cerndb/spark-dashboard#5]
Thank you very much 

You have done a great job and the documentation is also great 

Best regards,

**Comment by mdtmailgr** [comment]
Sorry you may close the ticket ;  all file 

You have done a great job and the documentation is also great

**Comment by LucaCanali** [comment]
Good to hear this is working for you know, thank you for the update.
